package com.jking31cs;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import com.jking31cs.state.BattleTree;
import com.jking31cs.state.Team;

/**
 * Data generated by the java program creating battle trees.
 */
public class GeneratedData {
    public Map<String, Team> teams = new HashMap<>();
    public Map<String, BattleTree> battleTrees = new HashMap<>();

    public Map<String, Set<String>> teamToBattleTreeIndex = new HashMap<>();

    public void addAllTeams(Map<String, Team> teams) {
        for (String id : teams.keySet()) {
            this.addTeam(teams.get(id));
        }
    }

    public void addTeam(Team team) {
        teams.put(team.getId(), team);
        teamToBattleTreeIndex.put(team.getId(), new HashSet<>());
    }

    public void addBattleTree(BattleTree battleTree) {
        battleTrees.put(battleTree.id, battleTree);
        teamToBattleTreeIndex.get(battleTree.states.get(battleTree.initialStateId).getT1Id()).add(battleTree.id);
    }

    public void addAllBattleTrees(Map<String, BattleTree> battleTrees) {
        battleTrees.values().forEach(this::addBattleTree);
    }
}
