/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jking31cs' at '10/11/16 9:06 PM' with Gradle 3.1
 *
 * @author jking31cs, @date 10/11/16 9:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
